### PR TITLE
Generalize detection of dat files

### PR DESCRIPTION
**Pull request by shawniverson**

### CODE REVIEW

**Comment by shawniverson** [comment]
Fixes #554

**Comment by janarzz** [comment]
I dont see any changes here: https://github.com/MailScanner/v5/pull/556/commits/cfb0221b51ad5e2a4b17e27d898370b7f1952f74

**Comment by janarzz** [comment]
I dont understand..line 900 is empty.

**Comment by shawniverson** [comment]
@janarzz We need to ensure the file is exact.  Maybe download https://raw.githubusercontent.com/MailScanner/v5/cfb0221b51ad5e2a4b17e27d898370b7f1952f74/common/usr/share/MailScanner/perl/MailScanner/SweepOther.pm and place it in /usr/share/MailScanner/perl/MailScanner (after backing up your old SweepOther.pm)

**Comment by janarzz** [comment]
New maillog here:
https://pilv.addit.ee/index.php/s/4H8THQo9Scj6mzc

**Comment by janarzz** [comment]
What is wrong my configuration ?

**Comment by shawniverson** [comment]
Have you restarted MailScanner recently?

**Comment by janarzz** [comment]
I restart mailscanner after any changes.

**Comment by shawniverson** [comment]
Yes, it is correct.

**Comment by janarzz** [comment]
Maybe must chnage another conf file or smth ?

**Comment by shawniverson** [comment]
@janarzz I'm going to build another mailscanner with the same version as yours and see if that makes any difference.

**Comment by shawniverson** [comment]
Refactor for user-defined extensions

**Comment by shawniverson** [comment]
Leaving this setting for just dat files, going to do a more generalized approach for other file types.

**Pull request merged**
