### PR TITLE
Remove CRs to allow unaltered delivery via QMQP

### PR DESCRIPTION
**Pull request by shawniverson**

### CODE REVIEW

**Comment by msapiro** [comment]
@shawniverson This looks good and passes my simple tests with both DKIM and PGP signed mail. However, with my #314 change, I still saw some DKIM failures with messages that passed at MailScanner SpamAssassin time. I have removed #314 and installed this one and will monitor.

I'm not sure what the issue might be, but perhaps some of these messages may have actual <CR> at the ends on lines in the signed body. If that's the case, I'm not sure what the solution might be if any.

**Comment by shawniverson** [comment]
@msapiro Keep me posted.  I'll hold off on the final testing round for now.

**Comment by msapiro** [comment]
@shawniverson So far it's working fine. I've seen a lot of delivered mail with valid DKIM sigs and the only invalid ones I've noticed are expected, i.e. ones that MailScanner has disarmed or otherwise modified.

**Comment by msapiro** [comment]
Still monitoring and it's still looking good.

**Pull request merged**
