### PR TITLE
Fixes for File MIME Types checking

### PR DESCRIPTION
**Pull request by gh0stwizard**
Hello,

This is a patch for File MIME Types checking. Two issues were fixed:
1. MIME types checking is skipped entirely in the case when in the configuration file any of options `Allow File MIME Types`, `Archives: Allow File MIME Types` have a value, but both of options `Deny File MIME Types` and `Archives: Deny File MIME Types` have not.

2. The File MIME types code contains checking for the regular file type rules, but the same checking was already done before. This part was cut off.

The current logic of file types checking were adopted via using a hash (`%deleted` in the patch):
1. Regular file types checking completed.
2. After that if enabled MIME type checking, the last one overrides decisions made by regular file types checking.
3. Unsafe files will be deleted from a message according to the final result made by regular types checking and (if enabled) MIME type checking.

The part of which I am not sure is it correct to delete a report as I did (an example below):
```perl
            delete $message->{namereports}{$safename};
            delete $message->{nametypes}{$safename};
```
Perhaps I am wrong, please, review this part and correct if needed.

Thank you.

### CODE REVIEW

**Comment by shawniverson** [comment]
Regression testing this PR before inclusion.

**Comment by gh0stwizard** [comment]
@shawniverson 
Do I have to write a regression test? Either, you will do it?

**Comment by shawniverson** [comment]
@gh0stwizard 
No.  MailScanner does not have a test suite.  I will pull the code in and test manually.  If I identify and regressions, I will post to this PR with recommendations.

**Comment by shawniverson** [comment]
No regressions found.

**Pull request merged**
