### PR TITLE
Support enable_original_recipient no

### PR DESCRIPTION
**Pull request by shawniverson**

### CODE REVIEW

**Comment by shawniverson** [comment]
Fixes #200

**Comment by dobril-stanga** [comment]
Unfortunately , it not show correct result for **To**.
Let me describe how I'm testing.
Send email few group emails in same message.
`echo "TestMail K1" |mail -s "TestMail K1" -c admin@snowthunder.org,admins@snowthunder.org xxx@snowthunder.org,dobril@snowthunder.org,test@snowthunder.org`

admin@ , admins@ , xxx@  are group emails ,with recepients dobril@  , test@

This is the mail header
```
Received: from mail.stanga.net (unknown [195.34.122.2])
     (using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))
     (No client certificate requested)
     by mail.snowthunder.org (Postfix) with ESMTPS id 56951626C4;
     Fri, 13 Jul 2018 12:01:58 +0300 (EEST)
Received: by mail.stanga.net (Postfix, from userid 0)
     id 3571630A0A81; Fri, 13 Jul 2018 12:01:52 +0300 (EEST)
Date: Fri, 13 Jul 2018 12:01:52 +0300
To: test@snowthunder.org, dobril@snowthunder.org, xxx@snowthunder.org
Cc: admins@snowthunder.org, admin@snowthunder.org
Subject: TestMail K1
User-Agent: Heirloom mailx 12.4 7/29/08
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Message-Id: <20180713090152.3571630A0A81@mail.stanga.net>
From: root@mail.stanga.net (root)
X-Stanga-MailScanner-ID: 3571630A0A81.A7C60
X-Stanga-MailScanner: Not scanned: please contact your Internet E-Mail Service Provider for details
X-Stanga-MailScanner-SpamCheck: not spam (whitelisted),
     SpamAssassin (score=-0.001, required 5, autolearn=disabled,
     NO_RELAYS -0.00)
X-Stanga-MailScanner-From: root@mail.stanga.net
X-Spam-Status: No
```
This is the value in To: dobril@snowthunder.org , test@snowthunder.org

Expected to be : admin@snowthunder.org, admins@snowthunder.org, xxx@snowthunder.org, dobril@snowthunder.org, test@snowthunder.org

**Comment by shawniverson** [comment]
cc's do not appear as to: addresses, but just to confirm, xxx@snowthunder.org didn't show?

**Comment by dobril-stanga** [comment]
Unfortunately not show.
enable_original_recipient=yes - All addresses appears correctly

Message Headers: | Received: from mail.stanga.net (unknown [195.34.122.2])     (using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))     (No client certificate requested)     by mail.snowthunder.org (Postfix) with ESMTPS id A9C23626BC;     Thu, 12 Jul 2018 16:25:53 +0300 (EEST)Received: by mail.stanga.net (Postfix, from userid 0)     id 7A16D30A0AC4; Thu, 12 Jul 2018 16:25:52 +0300 (EEST)Date: Thu, 12 Jul 2018 16:25:52 +0300To: test@snowthunder.org, dobril@snowthunder.org, xxx@snowthunder.orgCc: admins@snowthunder.org, admin@snowthunder.orgSubject: TestMail J2User-Agent: Heirloom mailx 12.4 7/29/08MIME-Version: 1.0Content-Type: text/plain; charset=us-asciiContent-Transfer-Encoding: 7bitMessage-Id: <20180712132552.7A16D30A0AC4@mail.stanga.net>From: root@mail.stanga.net (root)X-Stanga-MailScanner-ID: 7A16D30A0AC4.A8B8EX-Stanga-MailScanner: Not scanned: please contact your Internet E-Mail Service Provider for detailsX-Stanga-MailScanner-SpamCheck: not spam (whitelisted),     SpamAssassin (score=-0.001, required 5, autolearn=disabled,     NO_RELAYS -0.00)X-Stanga-MailScanner-From: root@mail.stanga.netX-Spam-Status: No
-- | --
From: | root@mail.stanga.net[Add to Whitelist \| Add to Blacklist] | root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
To: | test@snowthunder.orgxxx@snowthunder.orgadmin@snowthunder.orgdobril@snowthunder.orgadmins@snowthunder.org
Subject: | TestMail J2

enable_original_recipient=no - Show only final addresses , after postfix stripe mail groups. This is not OK  because if need to Release from quarantine , it will show different addressees.  Looks like MailScanner or Mailwatch is not intended to work with enable_original_recipient=no , unfortunately there are no much duplicated mails without this option.


Message Headers: | Received: from mail.stanga.net (unknown [195.34.122.2])     (using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))     (No client certificate requested)     by mail.snowthunder.org (Postfix) with ESMTPS id 56951626C4;     Fri, 13 Jul 2018 12:01:58 +0300 (EEST)Received: by mail.stanga.net (Postfix, from userid 0)     id 3571630A0A81; Fri, 13 Jul 2018 12:01:52 +0300 (EEST)Date: Fri, 13 Jul 2018 12:01:52 +0300To: test@snowthunder.org, dobril@snowthunder.org, xxx@snowthunder.orgCc: admins@snowthunder.org, admin@snowthunder.orgSubject: TestMail K1User-Agent: Heirloom mailx 12.4 7/29/08MIME-Version: 1.0Content-Type: text/plain; charset=us-asciiContent-Transfer-Encoding: 7bitMessage-Id: <20180713090152.3571630A0A81@mail.stanga.net>From: root@mail.stanga.net (root)X-Stanga-MailScanner-ID: 3571630A0A81.A7C60X-Stanga-MailScanner: Not scanned: please contact your Internet E-Mail Service Provider for detailsX-Stanga-MailScanner-SpamCheck: not spam (whitelisted),     SpamAssassin (score=-0.001, required 5, autolearn=disabled,     NO_RELAYS -0.00)X-Stanga-MailScanner-From: root@mail.stanga.netX-Spam-Status: No
-- | --
From: | root@mail.stanga.net[Add to Whitelist \| Add to Blacklist] | root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
root@mail.stanga.net | [Add to Whitelist \| Add to Blacklist]
To: | dobril@snowthunder.orgtest@snowthunder.org
Subject: | TestMail K1

**Comment by Skywalker-11** [comment]
The Problem is that MailScanner stores the original mail wich will then be released. If you want to do the deduplication also on the released mail you can setup a distinct port in postfix that will not be scanned by MailScanner again. Eg. add to the end of your postfixs master.cf
```
11550       inet  n       -       y       -       -       smtpd
    -o receive_override_options=no_header_body_checks
```
And set `define('MAILWATCH_MAIL_PORT', '11550');` in MailWatch conf.php accordingly.

Would that solve your problem?

**Comment by dobril-stanga** [comment]
I didn't understand how this can help :). Anyway I try it and all is like before, nothing changed.

**Pull request merged**
