### PR TITLE
7zip support

### PR DESCRIPTION
**Pull request by shawniverson**
Issue #117 
Big thanks to @spec1re for the code, only minor changes made.

### CODE REVIEW

**Comment by shawniverson** [comment]
Regression and 7zip functionality testing in progress

**Comment by shawniverson** [comment]
CentOS 6.9 tests (p7zip + p7zip-plugins)
Regression test pass: zip, rar
Pass:  7z, tar, wim, tar.gz, tar.bz2, tar.xz

Todo: identify p7zip packages for each distro and add to install.sh logic
CentOS 6 (epel)/7: p7zip, p7zip-plugins
Ubuntu: 
Debian:
SuSE:

**Comment by spec1re** [comment]
FreeBSD (pfSense): p7zip (/usr/local/bin/7z)

**Comment by shawniverson** [comment]
install scripts updated

**Pull request merged**
