### PR TITLE
Install script fixes

### PR DESCRIPTION
**Pull request by endelwar**
This change is [Reviewable](https://reviewable.io/reviews/mailscanner/v5/30)

### CODE REVIEW

**Comment by jcbenton** [comment]
These are incorrect and do not work on Ubuntu: $(grep ^7 /etc/debian_version)

I trusted your submission because your work on Mailwatch. I assumed you would have tested this across multiple Debian variants. Apparently, you did not.

**Comment by endelwar** [comment]
I did, on 14.04 and 16.04 (last 2 LTS version).
The problem occur only in debian 7 where an `apt-get install sendmail` is not sufficient to install sendmail
On ubuntu 14.04 and 16.04 the grep test correctly set MTAOPTION to "sendmail"

**Comment by jcbenton** [comment]
I will review and test it again. The --force-depends appears to be incorrect syntax for apt-get.

**Comment by endelwar** [comment]
$NODEPS is used only in with dpkg command (which is used to install mailscanner .deb file) not on apt-get one's (which installs mta, clamav and others, but not mailscanner)

```
root@ms-ubuntu-14:~# dpkg --force-help
dpkg forcing options - control behaviour when problems found:
  warn but continue:  --force-<thing>,<thing>,...
  stop with error:    --refuse-<thing>,<thing>,... | --no-force-<thing>,...
 Forcing things:
  [!] all                Set all force options
  [*] downgrade          Replace a package with a lower version
      configure-any      Configure any package which may help this one
      hold               Process incidental packages even when on hold
      not-root           Try to (de)install things even when not root
      bad-path           PATH is missing important programs, problems likely
      bad-verify         Install a package even if it fails authenticity check
      bad-version        Process even packages with wrong versions
      overwrite          Overwrite a file from one package with another
      overwrite-diverted Overwrite a diverted file with an undiverted version
  [!] overwrite-dir      Overwrite one package's directory with another's file
  [!] unsafe-io          Do not perform safe I/O operations when unpacking
  [!] confnew            Always use the new config files, don't prompt
  [!] confold            Always use the old config files, don't prompt
  [!] confdef            Use the default option for new config files if one
                         is available, don't prompt. If no default can be found,
                         you will be prompted unless one of the confold or
                         confnew options is also given
  [!] confmiss           Always install missing config files
  [!] confask            Offer to replace config files with no new versions
  [!] architecture       Process even packages with wrong or no architecture
  [!] breaks             Install even if it would break another package
  [!] conflicts          Allow installation of conflicting packages
  [!] depends            Turn all dependency problems into warnings
  [!] depends-version    Turn dependency version problems into warnings
  [!] remove-reinstreq   Remove packages which require installation
  [!] remove-essential   Remove an essential package

WARNING - use of options marked [!] can seriously damage your installation.
Forcing options marked [*] are enabled by default.
```

**Comment by jcbenton** [comment]
Good point :)

**Comment by endelwar** [comment]
:)
Did I regain your trust (even if I work on MailWatch?) ;) ;) ;)

**Comment by jcbenton** [comment]
It is being changed to just this because the package is present in all of the distributions:

MTAOPTION="sendmail sendmail-bin";

**Pull request merged**
