### PR TITLE
MailScanner 5.1.1-1

### PR DESCRIPTION
**Pull request by shawniverson**
- Milter support option for MailScanner
- Fix postfix long queue ids getting suffixed with key
- MailScanner Milter Documentation

### CODE REVIEW

**Comment by Skywalker-11** [comment]
I guess it doesn't have anything to do with `Microsoft Mail (or MSMail) was the name given to several early Microsoft e-mail products for local area networks, primarily two architectures...` https://en.wikipedia.org/wiki/Microsoft_Mail 😁

**Comment by shawniverson** [comment]
@Skywalker-11 MS=MailScanner but yeah, didn't draw the connection, forgot all about those days.

**Comment by Skywalker-11** [comment]
I have a few questions/observations:
* Can you add an the option to configure the milter as install parameter or to disable the question?
* If a mail is sent from the same server (via localhost ip eg. `swaks -t 127.0.0.1:25`) the milter reports `Localhost relay detected` in debug mode and the mail is stuck in postfix hold queue (/var/spool/postfix/hold)
* If mail is sent from the same server via public ip (eg `swaks -t 10.10.10.2:25`) the milter relays it to the MailScanner process (moved to /var/spool/MailScanner/milterin) but that reports `Syntax error in Postfix queue file, didn't start with a C record`. 
 ** The log entry is repeated every 1-5 seconds for each mail stuck there. 
 ** The mail also doesn't show up in mailq anymore (not in any postfix known queue). 
 ** In debug mode the MailScanner process is stuck at `Building a message stack to scan` but the log is normal till `Using locktype = flock` but then keeps repeating the `Synax error in Postfix...` every 5 seconds. 
 ** The log entries stop when the debug process is stopped
* What is with the ipv6 localhost `::1` for `/^Received:.*\(localhost\ \[127.0.0.1/ IGNORE` ? Also wouldn't this also remove headers from external servers that have this line? By RFC this must not be done:

https://tools.ietf.org/html/rfc5321#section-3.6.3
``` 
As discussed in Section 6.4, a relay SMTP has no need to inspect or
   act upon the header section or body of the message data and MUST NOT
   do so except to add its own "Received:" header field (Section 4.4)
   and, optionally, to attempt to detect looping in the mail system (see
   Section 6.3).  Of course, this prohibition also applies to any
   modifications of these header fields or text (see also Section 7.9).
```

https://tools.ietf.org/html/rfc5321#section-3.7.2

```
When forwarding a message into or out of the Internet environment, a
   gateway MUST prepend a Received: line, but it MUST NOT alter in any
   way a Received: line that is already in the header section.```

**Comment by shawniverson** [comment]
@Skywalker-11 

Simple fix for removing the correct Received entry is to be more specific.  I'm going to update the documentation.

```
/^Received:\ from\ <yourfqn>\ \(localhost\ \[127.0.0.1/ IGNORE
```

Where <yourfqdn> is the fully qualified domain name of your local host as it appears in the header.

**Comment by Skywalker-11** [comment]
> Check your header_checks file. When the milter is used, nothing should enter the hold queue unless postfix is sending it there because there's an entry to HOLD it.

You are right. Silly me had an additional header_check in a separate file.

>This would happen if you attempting to use the milter but have postfix processor as the mta instead of msmail as the mta. The milter should not be used at all if you are using the existing postfix processor.

Duplicate MTA entry in conf.d directory... Its working now

**Pull request merged**
