### PR TITLE
Flag hidden URL disarm

### PR DESCRIPTION
**Pull request by shawniverson**
Fix Issue #398

### CODE REVIEW

**Comment by shawniverson** [comment]
Refactor, also triggering unconditionally on matching URLs

**Comment by asuweb** [comment]
Doesn't compile on my test machine

```
Global symbol "$squashedtext" requires explicit package name at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8012.
Global symbol "$linkurl" requires explicit package name at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8013.
Global symbol "$squashedtext" requires explicit package name at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8014.
Global symbol "$linkurl" requires explicit package name at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8014.
syntax error at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8024, near "} elsif"
Global symbol "$text" requires explicit package name at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8026.
Global symbol "$text" requires explicit package name at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8029.
Unmatched right curly bracket at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8031, at end of line
BEGIN not safe after errors--compilation aborted at /usr/share/MailScanner/perl/MailScanner/Message.pm line 8178.
Compilation failed in require at /usr/sbin/MailScanner line 107.
BEGIN failed--compilation aborted at /usr/sbin/MailScanner line 107.
```

**Comment by shawniverson** [comment]
Checking...probably missed a bracket from my test env.

**Comment by shawniverson** [comment]
Fixed, try again.

**Pull request merged**
