### PR TITLE
Unrar v5: use vt command to detect encrypted files

### PR DESCRIPTION
**Pull request by giosh94mhz**
I've found some issue in detecting password protected files inside unrar archive, so I've made this changes.

The problem arise since Unrar can generate "fully-encrypted" files or "plain text filenames and encrypted content" archive.

So, I've simplified the unrar v5 routine by using "vt" (verbose tecnical) output of unrar, instead of "v" (verbose, simple table) output. An example output from "vt" is the following:

```
Archive: rar/putty.rar
Details: RAR 5

        Name: putty.exe
        Type: File
        Size: 524288
 Packed size: 248096
       Ratio: 47%
       mtime: 2015-12-24 10:21:43,389
  Attributes: ..A....
   CRC32 MAC: 2F458ECF
     Host OS: Windows
 Compression: RAR 5.0(v50) -m3 -md=1M
       Flags: encrypted 
```

As opposed to:

```
Archive: rar/putty.rar
Details: RAR 5

 Attributes      Size    Packed Ratio    Date    Time   Checksum  Name
----------- ---------  -------- ----- ---------- -----  --------  ----
*   ..A....    524288    248096  47%  2015-12-24 10:21  2F458ECF  putty.exe
----------- ---------  -------- ----- ---------- -----  --------  ----
               524288    248096  47%                              1
```

As you can see, the second output don't include "encrypted" flags. Also note, that in my code I split based on `\n\n`, so I could easily parse the "ArchiveInfo" section which is skipped in the current implementation.

I've tested with a lot of RAR files: correct, corrupted and encrypted. Everything seems to work to me. Keep in mind that I tested unrar 4-5 against mailscanner v4, and than migrated to v5; maybe is better test it again before merge.

Also, the block for corrupted files could be improved, by calling `unrar` a single time, but I wait for your feedback before changing the whole codebase :)

Final question: is the support to unrar 4, still useful nowadays? I think is 3 years since the release of v5...

### CODE REVIEW

**Comment by shawniverson** [comment]
Tested good on MailScanner v 5.0.3-7 using unrar 5.21.

**Comment by giosh94mhz** [comment]
Thank you @shawniverson for testing.

Anyway, I've just discovered an option of MailScanner called Check Password Protected file names (or similar, internally called `checkppafilenames`) which may not work with this implementation. When this option is true, empty files should be created for encrypted filename checks, but since I return inside the loop, this is not working anymore.

I'll change the code ASAP.

**Comment by giosh94mhz** [comment]
I was wrong about option `checkppafilenames`, the current behaviour is correct. This option comes in place if the password-protected archive are neither denied or required, so my checks are ok.

PS: the code of `UnpackRar` could be greatly optimized (e.g. not checking twice for enc files, not forking too much), but I won't do that now, since the support for unrar 4 is in the way.

**Comment by jcbenton** [comment]
I know this is old, but where are we at with this? Testing done, etc?

**Comment by giosh94mhz** [comment]
I'm using (a backport of) this in production from 2-3 months now without issues.

**Comment by shawniverson** [comment]
Tested here quite a while ago, works and addresses the issue.  I'll be
happy to give one more review to refresh my memory and ensure all is well.

**Pull request merged**
